name: Node.js CI

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    # Checks out a copy of your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Sets up Node.js environment
    - name: Set up Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    # Installs dependencies
    - name: Install dependencies
      run: npm install

    # Runs tests
    - name: Run tests
      run: npm test

